In [1]:
import shutil
import os

In [2]:
path_dir = r'C:\Users\user\Desktop\AI-based-Dementia-Severity-Prediction\dataset\raw_data\SNSB_png'
os.chdir(path_dir)

In [3]:
file_list = os.listdir()

In [4]:
print('디렉토리 내 전체 데이터 개수 :', len(file_list))

디렉토리 내 전체 데이터 개수 : 7512

In [5]:
count = 0
for i in file_list :
    if (i[-3:] in ['PNG', 'png']) and ('_' in i) :
        count+=1
print('유효 데이터 개수 :', count, '/', len(file_list))

유효 데이터 개수 : 7505 / 7512

In [8]:
count_sum = 0
for n in range(1,8):
    count = 0
    for i in file_list :
        if (i[-3:] in ['PNG', 'png']) and ('_%d' %n in i) and ('(' not in i) and (len(i) == 14) :
            count += 1
            count_sum += 1
    print('검사%d 데이터 수 :' %n, count)
print('총 검사 데이터 수 :', count_sum)

검사1 데이터 수 : 951
검사2 데이터 수 : 951
검사3 데이터 수 : 916
검사4 데이터 수 : 915
검사5 데이터 수 : 959
검사6 데이터 수 : 960
검사7 데이터 수 : 959
총 검사 데이터 수 : 6611

In [10]:
count_sum = 0
for n in range(1,8):
    count = 0
    for i in file_list :
        if (i[-3:] in ['PNG', 'png']) and ('_%d' %n in i) and ('(' not in i) and (len(i) == 14) :
            shutil.copy(i, r'C:\Users\user\Desktop\AI-based-Dementia-Severity-Prediction\dataset\%d' %n)
            count+=1
    print('복사 된 검사%d 데이터 수 :' %n, count)

복사 된 검사1 데이터 수 : 951
복사 된 검사2 데이터 수 : 951
복사 된 검사3 데이터 수 : 916
복사 된 검사4 데이터 수 : 915
복사 된 검사5 데이터 수 : 959
복사 된 검사6 데이터 수 : 960
복사 된 검사7 데이터 수 : 959

In [11]:
# 검사 4 기준 환자 번호 리스트 제작
path_dir = r'C:\Users\user\Desktop\AI-based-Dementia-Severity-Prediction\dataset\4'
os.chdir(path_dir)
file_list = os.listdir()

count = 0
hospital_no_4 = []
for i in file_list :
    if (i[-6:] in ['_4.PNG', '_4.png']) :
        count += 1
    assert len(i) == 14
    hospital_no_4.append(i[0:8])
assert len(hospital_no_4) == len(set(hospital_no_4)) == count
print(len(hospital_no_4), hospital_no_4[0:10])

915 ['00000323', '00001809', '00018693', '00028236', '00041427', '00048377', '00050941', '00058064', '00076105', '00088360']

In [20]:
import pandas as pd
import warnings
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
warnings.filterwarnings('ignore')

In [57]:
path_dir = r'C:\Users\user\Desktop\AI-based-Dementia-Severity-Prediction\preprocessing'
os.chdir(path_dir)

In [58]:
df = pd.read_csv('SNSB_1_figure_for4.csv')

In [59]:
df

      고유번호 Hospital No Luria_loop  CDR  Sum_of_boxes
0     2285      938443     Normal  1.0           8.0
1     2284     1407055     Normal  1.0           6.0
2     2283      970997     Normal  0.5           1.5
3     2282      991395     Normal  0.5           2.5
4     2281      891889     Normal  0.5           2.5
...    ...         ...        ...  ...           ...
2226     9      804535        PSV  1.0           4.5
2227     8      804535        PSV  1.0           4.5
2228     6     1076477     Normal  2.0          10.0
2229     5      735018     Normal  0.5           2.0
2230     4      735018     Normal  0.5           2.5

[2231 rows x 5 columns]

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2231 entries, 0 to 2230
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   고유번호          2231 non-null   int64
 1   Hospital No   2229 non-null   object
 2   Luria_loop    2051 non-null   object
 3   CDR           2213 non-null   float64
 4   Sum_of_boxes  2206 non-null   float64
dtypes: float64(2), int64(1), object(2)
memory usage: 87.3+ KB

In [61]:
df.drop(['CDR', 'Sum_of_boxes'], axis = 1, inplace = True)

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2231 entries, 0 to 2230
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   고유번호         2231 non-null   int64
 1   Hospital No  2229 non-null   object
 2   Luria_loop   2051 non-null   object
dtypes: int64(1), object(2)
memory usage: 52.4+ KB

In [63]:
df.dropna(subset=['Luria_loop', 'Hospital No'], inplace = True)

In [64]:
df.reset_index(inplace=True)

In [65]:
df.drop(['index'], axis = 1, inplace = True)

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2050 entries, 0 to 2049
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   고유번호         2050 non-null   int64
 1   Hospital No  2050 non-null   object
 2   Luria_loop   2050 non-null   object
dtypes: int64(1), object(2)
memory usage: 48.2+ KB

In [76]:
hospital_no_4 = list(map(int, hospital_no_4))

In [90]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2049 entries, 0 to 2048
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   고유번호         2049 non-null   int64
 1   Hospital No  2049 non-null   object
 2   Luria_loop   2049 non-null   object
dtypes: int64(1), object(2)
memory usage: 48.1+ KB

In [55]:
for i in range(len(df)):
    print()
    if int(df.loc[i]['Hospital No']) in hospital_no_4:
        pass
    else:
        print('ab')

ab






























































ab









ab























ab



ab


ab


ab

ab





ab

ab

ab


ab

ab



ab

ab

ab


ab

ab

ab

ab

ab

ab


ab


ab


ab

ab

ab

ab

ab

ab

ab

ab

ab

ab

ab

ab

ab

ab

ab

ab

ab


ab


ab

ab

ab





















ab
























ab

ab

ab

ab

ab

ab


ab

ab

ab

ab

ab

ab

ab

ab

ab

ab

ab



ab

ab

ab

ab

ab

ab

ab

ab


ab

ab

ab

ab



ab










ab

ab


ab

ab

ab

ab

ab


ab












ab

ab

ab

ab

ab

ab

ab



ab

ab

ab

ab

ab

ab

ab

ab

ab

ab

ab


ab

ab


ab

ab

ab



ab

ab

ab

ab

ab


ab

ab

ab


ab

ab


ab

ab

ab

ab

ab


ab


ab

ab

ab

ab

ab

ab



ab


ab

ab

ab

ab

ab




ab








ab

ab

ab

ab

ab

ab

ab

ab

ab

ab






ab



ab


ab


ab
























ab


ab




ab


ab

ab

ab


ab

ab






ab




ab




ab













ab








ab












ab

























ab





























ab















ab






ab





ab

















ab








































ab

ab

ab

ab

ab

ab


ab














ab







ab


ab

ab

ab

ab

ab

ab













ab




























ab













ab

ab









































ab

ab

ab

ab

ab

ab

ab

ab




ab

ab

ab

ab

ab

ab

ab

ab

ab

ab

ab

ab




ab

ab

ab




ab










ab









ab



ab


ab

ab

ab




ab



ab



ab

ab

ab

ab

ab

ab

ab

ab


ab

ab

ab

ab

ab






ab

ab

ab

ab

ab


ab



ab

ab


ab


ab



ab

ab

ab

ab

ab

ab


ab

ab

ab

ab

ab




ab

ab

ab

ab


ab

ab












ab

ab

ab

ab

ab

ab

ab


ab
















































































ab







ab

























ab














ab
















ab






ab

ab




ab

ab







ab


ab







ab


ab



ab


ab


ab

ab






ab



ab








ab





































ab







ab

ValueError: invalid literal for int() with base 10: '01-07369'

In [91]:
for i in range(len(df)):
    if int(df.loc[i]['Hospital No']) in hospital_no_4:
        pass
    else:
        df.drop(index=i, axis=0, inplace=True)

In [92]:
df

      고유번호 Hospital No Luria_loop
0     2285      938443     Normal
1     2284     1407055     Normal
2     2283      970997     Normal
3     2282      991395     Normal
4     2281      891889     Normal
...    ...         ...        ...
1986    69      112176     Normal
1992    63      403084        PSV
2008    47      853607     Normal
2009    46      853607     Normal
2011    44      899380     Normal

[1089 rows x 3 columns]

In [97]:
df.drop_duplicates(['Hospital No'], keep=False, inplace = True)

In [100]:
len(list(df['Hospital No'])) == len(set(df['Hospital No'])) == 666

True

In [101]:
arr = list(df['Hospital No'])

In [107]:
arr

[938443,
 1407055,
 991395,
 930331,
 1244209,
 884635,
 782437,
 270362,
 406495,
 707209,
 845032,
 869860,
 794793,
 815396,
 606325,
 711517,
 611747,
 998156,
 855327,
 275902,
 1077768,
 701694,
 622249,
 386210,
 1464462,
 1137650,
 1444938,
 600530,
 1034585,
 297688,
 904296,
 1383688,
 192974,
 1088674,
 454294,
 621597,
 813676,
 743257,
 1320922,
 956149,
 687556,
 1124557,
 1457505,
 1353330,
 951712,
 1453571,
 856489,
 1360770,
 773865,
 889931,
 394200,
 1298366,
 834803,
 723110,
 780973,
 1451391,
 486105,
 674106,
 735480,
 1238327,
 1453856,
 308691,
 942023,
 826861,
 832911,
 474121,
 1436758,
 1006707,
 766838,
 1001138,
 325929,
 640147,
 779511,
 1443011,
 671540,
 721815,
 1429282,
 1033535,
 861148,
 813343,
 1101799,
 605972,
 1074516,
 88360,
 1159856,
 1328203,
 876362,
 1391231,
 721042,
 963680,
 1035162,
 713432,
 1408259,
 979237,
 1201687,
 344581,
 1220981,
 1289362,
 810539,
 1090425,
 752045,
 297941,
 823509,
 977111,
 613313,
 603379,
 406528,
 722143,
 673505,
 427010,
 1404500,
 176514,
 1051833,
 257311,
 661887,
 1035156,
 396894,
 899695,
 1126879,
 742123,
 1109570,
 1363760,
 661966,
 901507,
 1403371,
 857366,
 708122,
 1401395,
 1333917,
 949841,
 941649,
 1287702,
 611999,
 1318352,
 1400725,
 1116389,
 450712,
 896042,
 1399351,
 856756,
 290547,
 622570,
 838660,
 1398739,
 891613,
 237065,
 909622,
 1398153,
 1216722,
 1303549,
 985827,
 915077,
 1389595,
 1297985,
 813176,
 1303479,
 510058,
 1398103,
 1216443,
 532295,
 236066,
 687918,
 952651,
 1085237,
 1052819,
 1369982,
 1368637,
 138259,
 1311440,
 1367005,
 1355297,
 945423,
 652151,
 617283,
 1365748,
 1367236,
 1364379,
 497382,
 779318,
 1237979,
 1359917,
 1364159,
 1321967,
 1092964,
 953291,
 141670,
 921088,
 769432,
 949983,
 1329575,
 1010362,
 1359686,
 766705,
 849146,
 998032,
 860667,
 1064650,
 625379,
 1025780,
 1203444,
 1130231,
 626173,
 951861,
 613052,
 1132092,
 323,
 803920,
 58064,
 298616,
 1027006,
 1246200,
 607615,
 1336722,
 704063,
 347313,
 764900,
 1275821,
 1131959,
 951701,
 1351393,
 1334787,
 874450,
 1178888,
 225424,
 612079,
 731508,
 1339759,
 815017,
 290240,
 1344212,
 1338710,
 938275,
 779709,
 1340347,
 1002918,
 917762,
 195824,
 622821,
 1108860,
 1338642,
 1293232,
 897985,
 958455,
 1310853,
 1336181,
 890434,
 1327814,
 676967,
 1342827,
 879020,
 1307058,
 954563,
 1332712,
 850889,
 941445,
 1278381,
 1199799,
 1336270,
 606999,
 1127904,
 953931,
 690996,
 1335435,
 1080207,
 1338557,
 760417,
 1182479,
 1285216,
 996941,
 607068,
 88513,
 759937,
 701917,
 526428,
 284102,
 948341,
 671379,
 1201045,
 916290,
 135376,
 1242449,
 258008,
 307906,
 1144046,
 378481,
 1325303,
 605579,
 658770,
 699051,
 909061,
 181474,
 984999,
 618081,
 389465,
 1331530,
 1277861,
 1312293,
 718582,
 1326000,
 1151163,
 860761,
 659353,
 1329469,
 733399,
 1129071,
 1319455,
 1285481,
 695821,
 815079,
 619387,
 781021,
 1155384,
 883363,
 715668,
 474262,
 955340,
 1297816,
 241549,
 1315776,
 613877,
 1251977,
 837432,
 957827,
 957862,
 609255,
 1206601,
 1314786,
 1270873,
 1306650,
 1311956,
 1041208,
 1306496,
 1310831,
 1191314,
 1292326,
 756851,
 382338,
 602435,
 646518,
 1311315,
 914229,
 1308862,
 869351,
 1302492,
 1077626,
 1057493,
 959479,
 1201052,
 360427,
 1305736,
 1306354,
 1306112,
 1174220,
 1243336,
 758152,
 1200378,
 1306520,
 724349,
 1231540,
 1135545,
 898995,
 1010278,
 1302485,
 600885,
 1277236,
 1303198,
 330967,
 417769,
 1302961,
 781879,
 1307080,
 1301982,
 1303957,
 1305203,
 885024,
 1307346,
 1303263,
 1252396,
 1294208,
 1292312,
 741780,
 887757,
 916343,
 1298517,
 1280762,
 1296102,
 1285505,
 784418,
 957757,
 1296342,
 1297715,
 771910,
 458897,
 1228443,
 1224642,
 1294084,
 354396,
 1248345,
 719738,
 430821,
 1259387,
 410742,
 631526,
 838991,
 898097,
 1257866,
 1031483,
 1276165,
 869642,
 950671,
 681823,
 1037729,
 1274318,
 608521,
 924187,
 754478,
 472638,
 621729,
 1095918,
 848444,
 1205381,
 1204901,
 179513,
 707204,
 1272624,
 723451,
 1271176,
 433123,
 861513,
 1242554,
 1201444,
 388436,
 925682,
 1273228,
 748566,
 1268545,
 1236217,
 372584,
 828485,
 228159,
 397703,
 1271272,
 1273149,
 532236,
 492040,
 1064676,
 1198479,
 1271874,
 1182545,
 1174216,
 692158,
 1184838,
 416574,
 1266829,
 1109474,
 740824,
 679999,
 676272,
 642008,
 617577,
 1262449,
 205252,
 388655,
 675437,
 233794,
 1242982,
 1261352,
 448360,
 191216,
 736916,
 1258625,
 757074,
 28236,
 601765,
 955605,
 743464,
 1020558,
 430974,
 623289,
 1249485,
 1255801,
 489204,
 927352,
 1078790,
 208408,
 787688,
 177836,
 758747,
 1256043,
 654225,
 951593,
 1082371,
 821552,
 1254619,
 1255785,
 916761,
 807838,
 444168,
 1233644,
 1250004,
 1026990,
 1054491,
 835619,
 611369,
 1228088,
 601028,
 743433,
 666473,
 180071,
 925914,
 1246279,
 772053,
 162025,
 838749,
 758208,
 123402,
 18693,
 1194196,
 606697,
 1195277,
 633197,
 1112291,
 617129,
 688094,
 1189271,
 342747,
 1243158,
 1223126,
 951389,
 451874,
 1020014,
 1240431,
 1029876,
 1234393,
 760139,
 1242981,
 1243940,
 719234,
 1234655,
 1017992,
 918741,
 1234183,
 926040,
 1234904,
 1234843,
 811805,
 645911,
 1009475,
 980333,
 1240949,
 433053,
 480780,
 1186557,
 791829,
 194586,
 791819,
 1204628,
 292674,
 1231246,
 205085,
 1067991,
 1171046,
 1228196,
 395714,
 965641,
 1086910,
 765867,
 709809,
 701646,
 1225367,
 1169939,
 423326,
 1215425,
 1224467,
 800927,
 1220764,
 1221176,
 1216731,
 1133534,
 530474,
 910838,
 1227860,
 1168853,
 1179897,
 944310,
 1130210,
 939372,
 335689,
 1222084,
 967248,
 1219287,
 927265,
 899614,
 1215115,
 1224786,
 319696,
 649045,
 624688,
 1168252,
 954051,
 834737,
 281543,
 933082,
 1210535,
 1212210,
 978843,
 114201,
 701424,
 1211540,
 955109,
 1173137,
 76105,
 1204692,
 882475,
 771131,
 1208946,
 41427,
 213490,
 1164481,
 912302,
 284872,
 641692,
 1058687,
 1152428,
 817022,
 743073,
 676993,
 672070,
 1014171,
 452201,
 1171567,
 654517,
 1200248,
 740750,
 740694,
 1031448,
 1200993,
 1193343,
 1196024,
 301478,
 1200384,
 725683,
 819719,
 680066,
 1098970,
 1197097,
 1036036,
 1177737,
 1194819,
 935668,
 780892,
 1199258,
 484899,
 1188626,
 945348,
 916546,
 752546,
 1193871,
 278087,
 164098,
 693697,
 339832,
 1191530,
 1168365,
 1154834,
 953442]

In [111]:
print('##### ENTER #####')
path_dir = r'C:\Users\user\Desktop\AI-based-Dementia-Severity-Prediction\preprocessing\4'
os.chdir(path_dir)
file_list = os.listdir()

del_count = 0
for i in file_list :
    if int(i[0:8]) in arr :
        pass
    else :
        os.remove(i)
        del_count += 1
print('삭제 데이터 수 :', del_count)
print('최종 데이터 수 :', len(os.listdir()))

##### ENTER #####
삭제 데이터 수 : 249
최종 데이터 수 : 666

In [112]:
file_list = os.listdir()
new_arr = []
for i in file_list :
    new_arr.append(int(i[0:8]))

In [117]:
set(arr) == set(new_arr)

True

In [119]:
df.drop(['고유번호'], axis=1, inplace=True)

In [148]:
df['Luria_loop'].value_counts()

Normal        541
PSV            76
Deformed       28
Deform&PSV     21
Name: Luria_loop, dtype: int64

In [150]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 666 entries, 0 to 665
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Hospital No  666 non-null    object
 1   Luria_loop   666 non-null    object
dtypes: object(2)
memory usage: 10.5+ KB

In [131]:
path_dir = r'C:\Users\user\Desktop\AI-based-Dementia-Severity-Prediction\preprocessing\4'
os.chdir(path_dir)
file_list = os.listdir()
len(file_list)

666

In [170]:
normal = list(map(int, list(df[df['Luria_loop'] == 'Normal']['Hospital No'])))
len(normal)

541

In [171]:
PSV = list(map(int, list(df[df['Luria_loop'] == 'PSV']['Hospital No'])))
len(PSV)

76

In [172]:
deformed = list(map(int, list(df[df['Luria_loop'] == 'Deformed']['Hospital No'])))
len(deformed)

28

In [173]:
deformPSV = list(map(int, list(df[df['Luria_loop'] == 'Deform&PSV']['Hospital No'])))
len(deformPSV)

21

In [174]:
for i in file_list :
    if int(i[0:8]) in normal:
        shutil.copy(i, r'C:\Users\user\Desktop\AI-based-Dementia-Severity-Prediction\CNN\Normal')
    elif int(i[0:8]) in PSV:
        shutil.copy(i, r'C:\Users\user\Desktop\AI-based-Dementia-Severity-Prediction\CNN\PSV')
    elif int(i[0:8]) in deformed:
        shutil.copy(i, r'C:\Users\user\Desktop\AI-based-Dementia-Severity-Prediction\CNN\Deformed')
    elif int(i[0:8]) in deformPSV:
        shutil.copy(i, r'C:\Users\user\Desktop\AI-based-Dementia-Severity-Prediction\CNN\Deform&PSV')
    else :
        print('ERROR! with %s' %i)